### ISSUE TITLE
Request for Reprint&Add Chinese version

### ISSUE THREAD

**Issue by lztttt** [JacobWKlein/JacobWKlein.github.io#4]
Hello
   I would like to translate your web page(PC-Building-Simulator-HTML-Calculator) into Chinese in order to be available to more players(in fact I am already working on the translation). 
  I will indicate the author on the page, and I will not profit.If you approve, I will hang it on my GitHub ,and keep updating.
 finally, thank you for the tool, it works very well!
[demo](https://lztttt.tk/pbs/)

**Comment by JacobWKlein** [comment]
This is fine by me, for now, but I may change my mind later. Thank you for contacting me. Good luck on the translations.

**Comment by Liliyord** [comment]
#5

**Comment by Liliyord** [comment]
me

**Comment by Liliyord** [comment]
#5

**Comment by Liliyord** [comment]
#5

**Comment by JacobWKlein** [comment]
Closing. Permission has been granted, to translate the page, with restrictions, as noted earlier.

**Comment by Liliyord** [comment]
.github/CODEOWNERS

**Comment by Liliyord** [comment]
#``

**Comment by Liliyord** [comment]
@fuzzyray

**Comment by Liliyord** [comment]
@JacobWKlein 

- [ ]
