### ISSUE TITLE
This is fine by me, for now, but I may change my mind later. Thank you for contacting me. Good luck on the translations.

### ISSUE THREAD

**Issue by Liliyord** [JacobWKlein/JacobWKlein.github.io#5]
This is fine by me, for now, but I may change my mind later. Thank you for contacting me. Good luck on the translations.

_Originally posted by @JacobWKlein in https://github.com/JacobWKlein/JacobWKlein.github.io/issues/4#issuecomment-1086667384_

**Comment by JacobWKlein** [comment]
No idea why this issue was created. #4 made sense.

**Comment by Liliyord** [comment]
Duplicate of #

**Comment by Liliyord** [comment]
.github/CODEOWNERS #4
